version: '3'

services:
  red:
    build: .
    container_name: linto-red
    image: linto/red
    ports:
      - 127.0.0.1:9000:9000
    env_file: .env
    networks:
     - internal

networks:
  internal: