version: '3.7'

services:
  red:
    build: .
    image: lintoai/linto-platform-business-logic-server
    container_name: linto-red
    deploy:
      mode: replicated
      replicas: 1
    env_file: .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
    #  - ./local-settings/settings.js:/usr/src/app/business-logic-server/lib/node-red/settings/settings.js
    #  - ./linto-skill/:/root/.node-red/node_modules/
    environment:
      - LINTO_STACK_BLS_HTTP_PORT=80 # Complete all of this for overrides
      - NODE_ENV="production"
      - LINTO_STACK_NPM_CUSTOM_REGISTRY="http://verdaccio.linto.ai"
    command: # Overrides CMD specified in dockerfile (none here, handled by entrypoint)
      #- --custom-registry-npmrc
      #- --registry-npmrc
      #- --run-cmd=DEBUG=* npm run start-dev
      - --run-cmd=npm run start
    networks:
      - linto-net

networks:
  linto-net:
    external: true